### ISSUE TITLE
rename repository

### ISSUE THREAD

**Issue by professor-enoqueleal** [LucasFernm/aplicacao-web-e-commerce-de-vinho#1]
Turma, por convenção, criamos os nomes de repositório no github utilizando apenas letras minúsculas (_lower camel case_) e separamos as palavras utilizando _hyphen_ ao invés de _underline_.

Sugiro fazer o _rename_ do repositório seguindo a convenção de nomeclatura.

**Comment by LucasFernm** [comment]
Ok! Obrigado pela explicação @professor-enoqueleal!
